import type { CrudPageConfig } from '@/components/CrudPage';

export const config: CrudPageConfig = {
  categoryId: 'ap-safety-inspection-non-conformity',
  title: 'Non-Conformity Inspection',
  description: 'Record inspeksi temuan ketidaksesuaian (unsafe action, unsafe condition, near miss) beserta tindak lanjut perbaikan.',
  parentLabel: 'Safety Inspection',
  enableApproval: true,
  fields: [
    // ── Identitas Inspeksi ──────────────────────────────────────────────
    {
      key: 'tanggalInspeksi',
      label: 'Inspection Date (Tanggal Inspeksi)',
      type: 'date',
      required: true,
      showInTable: true,
    },
    {
      key: 'safetyOfficer',
      label: 'Safety Officer',
      type: 'text',
      required: true,
      showInTable: true,
      placeholder: 'Safety officer name / ID',
    },
    {
      key: 'lokasiUtama',
      label: 'Main Location (Lokasi Utama)',
      type: 'select',
      required: true,
      showInTable: true,
      options: [
        { value: '140_hektar',  label: '140 HEKTAR (140亩)' },
        { value: '500_hektar',  label: '500 HEKTAR (500亩-第二选矿厂)' },
        { value: '86_selatan',  label: '86 SELATAN (南86)' },
        { value: '86_utara',    label: '86 UTARA (86区域)' },
        { value: 'area_57',     label: 'AREA 57 (57平区域)' },
        { value: 'imip_9',      label: 'IMIP 9 (新九区)' },
        { value: 'imip_8',      label: 'IMIP 8 (新八区)' },
        { value: 'km_3',        label: 'KM 3 (3公里)' },
        { value: 'km_6',        label: 'KM 6 (6公里)' },
        { value: 'jetty',       label: 'JETTY (中转罐、码头)' },
        { value: 'lainnya',     label: 'Other (Lainnya)' },
      ],
    },
    {
      key: 'areaInspeksiSpesifik',
      label: 'Specific Area (Area Inspeksi Spesifik)',
      type: 'text',
      required: true,
      showInTable: false,
      placeholder: 'e.g. Workshop A Line 2, Crusher Unit 3',
    },
    {
      key: 'qmbGroup',
      label: 'QMB Group / Contractor',
      type: 'select',
      required: true,
      showInTable: false,
      options: [
        { value: 'qmb',        label: 'QMB Group' },
        { value: 'kontraktor', label: 'Contractor (Kontraktor)' },
      ],
    },
    {
      key: 'namaDepartemen',
      label: 'Department / Company (Nama Departemen / Perusahaan)',
      type: 'text',
      required: true,
      showInTable: false,
      placeholder: 'Department or company name',
    },

    // ── Foto Hazard ─────────────────────────────────────────────────────
    {
      key: 'dokumentasiHazard',
      label: 'Hazard Documentation Photo (Foto Sebelum / 违规记录照片)',
      type: 'file',
      required: true,
      accept: 'image/*',
      showInTable: false,
      showInDetail: true,
    },

    // ── Klasifikasi Temuan ──────────────────────────────────────────────
    {
      key: 'jenisTemuan',
      label: 'Finding Type (Jenis Temuan)',
      type: 'select',
      required: true,
      showInTable: true,
      options: [
        { value: 'unsafe_action',    label: 'Unsafe Action' },
        { value: 'unsafe_condition', label: 'Unsafe Condition' },
        { value: 'near_miss',        label: 'Near Miss' },
      ],
    },
    {
      key: 'levelHazard',
      label: 'Hazard Level (Level Hazard)',
      type: 'select',
      required: true,
      showInTable: true,
      options: [
        { value: 'low',      label: 'Low' },
        { value: 'medium',   label: 'Medium' },
        { value: 'high',     label: 'High' },
        { value: 'critical', label: 'Critical' },
      ],
    },
    {
      key: 'tipeTemuan',
      label: 'Finding Category (Tipe Temuan)',
      type: 'select',
      required: true,
      showInTable: false,
      options: [
        { value: 'hazard', label: 'Hazard' },
        { value: '6s',     label: '6S Violation (Pelanggaran 6S)' },
      ],
    },
    // Conditional — only shown when tipeTemuan === 'hazard'
    {
      key: 'kategoriHazard',
      label: 'Hazard Category (Kategori Hazard)',
      type: 'select',
      required: false,
      showInTable: false,
      showWhen: { field: 'tipeTemuan', value: 'hazard' },
      options: [
        { value: '1',  label: '1. Hot Work (Pekerjaan Panas / 动火作业类)' },
        { value: '2',  label: '2. Confined Space (Ruang Terbatas / 受限空间类)' },
        { value: '3',  label: '3. Lifting Work (Pekerjaan Pengangkatan / 吊装作业类)' },
        { value: '4',  label: '4. Driving Safety (Keamanan Berkendara / 车辆安全类)' },
        { value: '5',  label: '5. Working at Heights (Pekerjaan Ketinggian / 高空作业类)' },
        { value: '6',  label: '6. Electrical Work (Pekerjaan Listrik / 用电安全类)' },
        { value: '7',  label: '7. Excavation Work (Pekerjaan Penggalian / 动土作业)' },
        { value: '8',  label: '8. Road Closure (Pembatasan Akses Jalan / 断路作业)' },
        { value: '9',  label: '9. Site Management (Manajemen Lokasi / 现场管理)' },
        { value: '10', label: '10. Hand & Power Tools (工具与作业器具类)' },
        { value: '11', label: '11. Heavy Equipment (Alat Berat & Mesin Bergerak / 重型设备与移动机械类)' },
        { value: '12', label: '12. Health & First Aid (Kesehatan & P3K / 健康与急救类)' },
        { value: '13', label: '13. Safety Signage & Communication (Komunikasi dan Rambu K3 / 安全标识与沟通类)' },
        { value: '14', label: '14. Traffic (交通)' },
        { value: '15', label: '15. Others (Lain-Lain / 其他)' },
      ],
    },
    // Conditional — only shown when tipeTemuan === '6s'
    {
      key: 'kategori6S',
      label: '6S Violation Category (Kategori Pelanggaran 6S)',
      type: 'select',
      required: false,
      showInTable: false,
      showWhen: { field: 'tipeTemuan', value: '6s' },
      options: [
        { value: '1',  label: '1. Floor (Lantai / 地面)' },
        { value: '2',  label: '2. Equipment (Peralatan / 设备)' },
        { value: '3',  label: '3. Material (材料、物料)' },
        { value: '4',  label: '4. Cabinet / Rack (Kabinet Wadah / 容器货架)' },
        { value: '5',  label: '5. Toolbox Cabinet (Kabinet Kotak Alat / 工具箱柜)' },
        { value: '6',  label: '6. Workbench (Meja Kerja / 工作台桌)' },
        { value: '7',  label: '7. Transport Tools (Alat Transportasi / 运输类工具)' },
        { value: '8',  label: '8. Corridor (Lorong / 通道)' },
        { value: '9',  label: '9. Walls / Windows / Doors (Dinding, Jendela & Pintu / 门窗墙壁)' },
        { value: '10', label: '10. Signage (Rambu / 标识牌)' },
        { value: '11', label: '11. Electrical Equipment (Peralatan Listrik / 电气设备)' },
        { value: '12', label: '12. Fire Facility (Fasilitas Kebakaran / 消防设施)' },
        { value: '13', label: '13. Regulations (Peraturan / 规章制度)' },
        { value: '14', label: '14. Cleaning Tools (Peralatan Kebersihan / 清洁用具)' },
        { value: '15', label: '15. PPE & Clothing (APD & Pakaian / 劳保用品、衣物)' },
        { value: '16', label: '16. Others (Lain-Lain / 其他)' },
      ],
    },

    // ── Deskripsi ────────────────────────────────────────────────────────
    {
      key: 'deskripsiKetidaksesuaian',
      label: 'Non-Conformity Description (Deskripsi Ketidaksesuaian / 不符合项描述)',
      type: 'textarea',
      required: true,
      showInTable: false,
      showInDetail: true,
      placeholder: 'Describe the non-conformity finding in detail...',
    },

    // ── Pengendalian & Perbaikan ─────────────────────────────────────────
    {
      key: 'hierarkiPengendalian',
      label: 'Control Hierarchy (Hirarki Pengendalian / 危险控制层级)',
      type: 'select',
      required: true,
      showInTable: false,
      options: [
        { value: 'eliminasi',                    label: 'Elimination (Eliminasi / 消除)' },
        { value: 'substitusi',                   label: 'Substitution (Substitusi / 替代)' },
        { value: 'pengendalian_teknik',          label: 'Engineering Control (Pengendalian Teknik / 工程控制)' },
        { value: 'pengendalian_administratif',   label: 'Administrative Control (Pengendalian Administratif / 管理控制)' },
        { value: 'apd',                          label: 'PPE (Alat Pelindung Diri / 个人防护装备)' },
      ],
    },
    {
      key: 'rekomendasiPerbaikan',
      label: 'Corrective Action Recommendation (Rekomendasi Perbaikan / 整改建议)',
      type: 'textarea',
      required: true,
      showInTable: false,
      showInDetail: true,
      placeholder: 'Describe the recommended corrective action...',
    },
    {
      key: 'deadlinePerbaikan',
      label: 'Correction Deadline (Deadline Perbaikan / 整改期限)',
      type: 'date',
      required: true,
      showInTable: true,
    },
    {
      key: 'picPerbaikan',
      label: 'Person in Charge — PIC (负责人)',
      type: 'text',
      required: true,
      showInTable: false,
      placeholder: 'PIC name',
    },

    // ── Foto Perbaikan ────────────────────────────────────────────────────
    {
      key: 'dokumentasiPerbaikan',
      label: 'Corrective Action Photo (Foto Sesudah / 整改图片)',
      type: 'file',
      required: false,
      accept: 'image/*',
      showInTable: false,
      showInDetail: true,
    },

    // ── Keterangan ────────────────────────────────────────────────────────
    {
      key: 'keteranganTambahan',
      label: 'Additional Notes (Keterangan Tambahan / 备注)',
      type: 'textarea',
      required: false,
      showInTable: false,
      showInDetail: true,
      placeholder: 'Additional notes or remarks...',
    },
  ],
};
