import type { CrudPageConfig } from '@/components/CrudPage';

export const config: CrudPageConfig = {
  categoryId: 'ap-safety-inspection-non-conformity',
  title: 'Non-Conformity Inspection',
  description: 'Record inspeksi temuan ketidaksesuaian (unsafe action, unsafe condition, near miss) beserta tindak lanjut perbaikan.',
  parentLabel: 'Safety Inspection',
  enableApproval: true,
  fields: [
    // ── Identitas Inspeksi ──────────────────────────────────────────────
    {
      key: 'tanggalInspeksi',
      label: 'Inspection Date',
      type: 'date',
      required: true,
      showInTable: true,
    },
    {
      key: 'safetyOfficer',
      label: 'Safety Officer',
      type: 'text',
      required: true,
      showInTable: true,
      placeholder: 'Safety officer name / ID',
    },
    {
      key: 'lokasiUtama',
      label: 'Main Location',
      type: 'select',
      required: true,
      showInTable: true,
      options: [
        { value: '140_hektar',  label: '140 HEKTAR (140亩)' },
        { value: '500_hektar',  label: '500 HEKTAR (500亩-第二选矿厂)' },
        { value: '86_selatan',  label: '86 SELATAN (南86)' },
        { value: '86_utara',    label: '86 UTARA (86区域)' },
        { value: 'area_57',     label: 'AREA 57 (57平区域)' },
        { value: 'imip_9',      label: 'IMIP 9 (新九区)' },
        { value: 'imip_8',      label: 'IMIP 8 (新八区)' },
        { value: 'km_3',        label: 'KM 3 (3公里)' },
        { value: 'km_6',        label: 'KM 6 (6公里)' },
        { value: 'jetty',       label: 'JETTY (中转罐、码头)' },
        { value: 'lainnya',     label: 'Other' },
      ],
    },
    {
      key: 'areaInspeksiSpesifik',
      label: 'Specific Area',
      type: 'text',
      required: true,
      showInTable: false,
      placeholder: 'e.g. Workshop A Line 2, Crusher Unit 3',
    },
    {
      key: 'qmbGroup',
      label: 'QMB Group / Contractor',
      type: 'select',
      required: true,
      showInTable: false,
      options: [
        { value: 'qmb',        label: 'QMB Group' },
        { value: 'kontraktor', label: 'Contractor' },
      ],
    },
    {
      key: 'namaDepartemen',
      label: 'Department / Company',
      type: 'text',
      required: true,
      showInTable: false,
      placeholder: 'Department or company name',
    },

    // ── Foto Hazard ─────────────────────────────────────────────────────
    {
      key: 'dokumentasiHazard',
      label: 'Hazard Documentation',
      type: 'file',
      required: true,
      accept: 'image/*',
      showInTable: false,
      showInDetail: true,
    },

    // ── Klasifikasi Temuan ──────────────────────────────────────────────
    {
      key: 'jenisTemuan',
      label: 'Finding Type',
      type: 'select',
      required: true,
      showInTable: true,
      options: [
        { value: 'unsafe_action',    label: 'Unsafe Action' },
        { value: 'unsafe_condition', label: 'Unsafe Condition' },
        { value: 'near_miss',        label: 'Near Miss' },
      ],
    },
    {
      key: 'levelHazard',
      label: 'Hazard Level',
      type: 'select',
      required: true,
      showInTable: true,
      options: [
        { value: 'low',      label: 'Low' },
        { value: 'medium',   label: 'Medium' },
        { value: 'high',     label: 'High' },
        { value: 'critical', label: 'Critical' },
      ],
    },
    {
      key: 'tipeTemuan',
      label: 'Finding Category',
      type: 'select',
      required: true,
      showInTable: false,
      options: [
        { value: 'hazard', label: 'Hazard' },
        { value: '6s',     label: '6S Violation' },
      ],
    },
    // Conditional — only shown when tipeTemuan === 'hazard'
    {
      key: 'kategoriHazard',
      label: 'Hazard Category',
      type: 'select',
      required: false,
      showInTable: false,
      showWhen: { field: 'tipeTemuan', value: 'hazard' },
      options: [
        { value: '1',  label: '1. Hot Work' },
        { value: '2',  label: '2. Confined Space' },
        { value: '3',  label: '3. Lifting Work' },
        { value: '4',  label: '4. Driving Safety' },
        { value: '5',  label: '5. Working at Heights' },
        { value: '6',  label: '6. Electrical Work' },
        { value: '7',  label: '7. Excavation Work' },
        { value: '8',  label: '8. Road Closure' },
        { value: '9',  label: '9. Site Management' },
        { value: '10', label: '10. Hand & Power Tools' },
        { value: '11', label: '11. Heavy Equipment' },
        { value: '12', label: '12. Health & First Aid' },
        { value: '13', label: '13. Safety Signage & Communication' },
        { value: '14', label: '14. Traffic' },
        { value: '15', label: '15. Others' },
      ],
    },
    // Conditional — only shown when tipeTemuan === '6s'
    {
      key: 'kategori6S',
      label: '6S Violation',
      type: 'select',
      required: false,
      showInTable: false,
      showWhen: { field: 'tipeTemuan', value: '6s' },
      options: [
        { value: '1',  label: '1. Floor' },
        { value: '2',  label: '2. Equipment' },
        { value: '3',  label: '3. Material' },
        { value: '4',  label: '4. Cabinet / Rack' },
        { value: '5',  label: '5. Toolbox Cabinet' },
        { value: '6',  label: '6. Workbench' },
        { value: '7',  label: '7. Transport Tools' },
        { value: '8',  label: '8. Corridor' },
        { value: '9',  label: '9. Walls / Windows / Doors' },
        { value: '10', label: '10. Signage' },
        { value: '11', label: '11. Electrical Equipment' },
        { value: '12', label: '12. Fire Facility' },
        { value: '13', label: '13. Regulations' },
        { value: '14', label: '14. Cleaning Tools' },
        { value: '15', label: '15. PPE & Clothing' },
        { value: '16', label: '16. Others' },
      ],
    },

    // ── Deskripsi ────────────────────────────────────────────────────────
    {
      key: 'deskripsiKetidaksesuaian',
      label: 'Non-Conformity Description',
      type: 'textarea',
      required: true,
      showInTable: false,
      showInDetail: true,
      placeholder: 'Describe the non-conformity finding in detail...',
    },

    // ── Pengendalian & Perbaikan ─────────────────────────────────────────
    {
      key: 'hierarkiPengendalian',
      label: 'Control Hierarchy',
      type: 'select',
      required: true,
      showInTable: false,
      options: [
        { value: 'eliminasi',                    label: 'Elimination' },
        { value: 'substitusi',                   label: 'Substitution' },
        { value: 'pengendalian_teknik',          label: 'Engineering Control' },
        { value: 'pengendalian_administratif',   label: 'Administrative Control' },
        { value: 'apd',                          label: 'PPE (Alat Pelindung Diri' },
      ],
    },
    {
      key: 'rekomendasiPerbaikan',
      label: 'Corrective Action Recommendation',
      type: 'textarea',
      required: true,
      showInTable: false,
      showInDetail: true,
      placeholder: 'Describe the recommended corrective action...',
    },
    {
      key: 'deadlinePerbaikan',
      label: 'Correction Deadline',
      type: 'date',
      required: true,
      showInTable: true,
    },
    {
      key: 'picPerbaikan',
      label: 'Person in Charge',
      type: 'text',
      required: true,
      showInTable: false,
      placeholder: 'PIC name',
    },

    // ── Foto Perbaikan ────────────────────────────────────────────────────
    {
      key: 'dokumentasiPerbaikan',
      label: 'Corrective Action Photo',
      type: 'file',
      required: false,
      accept: 'image/*',
      showInTable: false,
      showInDetail: true,
    },

    // ── Keterangan ────────────────────────────────────────────────────────
    {
      key: 'keteranganTambahan',
      label: 'Additional Notes',
      type: 'textarea',
      required: false,
      showInTable: false,
      showInDetail: true,
      placeholder: 'Additional notes or remarks...',
    },
  ],
};
